-- MySQL Script generated by MySQL Workbench
-- Fri Jun  7 22:41:56 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CarsDatabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CarsDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CarsDatabase` DEFAULT CHARACTER SET utf8 ;
USE `CarsDatabase` ;

-- -----------------------------------------------------
-- Table `CarsDatabase`.`cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarsDatabase`.`cars` (
  `id` INT AUTO_INCREMENT NOT NULL,
  `url_photo` VARCHAR(300) NULL,
  `name` VARCHAR(200) NULL,
  `price` VARCHAR(200) NULL,
  `engine` VARCHAR(200) NULL,
  `transmission` VARCHAR(200) NULL,
  `drive` VARCHAR(200) NULL,
  `body_type` VARCHAR(200) NULL,
  `color` VARCHAR(200) NULL,
  `mileage` VARCHAR(200) NULL,
  `wheel` VARCHAR(200) NULL,
  `url` VARCHAR(300) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
